plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.layered() {
        officialMojangMappings()
    }
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    compileOnly "org.ow2.asm:asm:9.10.1"
    compileOnly "org.ow2.asm:asm-tree:9.10.1"
    compileOnly "net.fabricmc:sponge-mixin:0.17.4+mixin.0.8.7"
    compileOnly "io.github.llamalad7:mixinextras-fabric:0.5.5"
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
    options.encoding = 'UTF-8'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

processResources {
    def props = [
            version                 : mod_version,
            mod_id                  : mod_id,
            mod_name                : mod_name,
            mod_license             : mod_license,
            mod_authors             : mod_authors,
            mod_description         : mod_description,
            minecraft_version_range : minecraft_version_range,
            loader_version_range    : loader_version_range]
    inputs.properties(props)
    filesMatching('fabric.mod.json') {
        expand(props)
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
}

apply from: 'realtime-native.gradle'
